# ---------------------------------- phone locatores ---------------------------------------------
class Home_page_locatores:
    samsung_galaxy_s6 = "/html/body/div[5]/div/div[2]/div/div[1]/div/a/img"
    nokiya_lumi = "/html/body/div[5]/div/div[2]/div/div[2]/div/a/img"
    nuxes_6 = "/html/body/div[5]/div/div[2]/div/div[3]/div/a/img"
    samsung_galaxy_s7 = "/html/body/div[5]/div/div[2]/div/div[4]/div/a/img"
    iphone_32gb = "/html/body/div[5]/div/div[2]/div/div[5]/div/a/img"
    sony_xpria_Z5 = "/html/body/div[5]/div/div[2]/div/div[6]/div/a/img"
    Htc_one_M9 = "/html/body/div[5]/div/div[2]/div/div[7]/div/a/img"
    add_cart = "Add to cart"
    cart_button = "//a[@id='cartur']"
    title_samsung = "//td[contains(text(),'Samsung galaxy s6')]"
    title_nexus = "/html/body/div[6]/div/div[1]/div/table/tbody/tr/td[2]"
    title_xpria = "//td[contains(text(),'Sony xperia z5')]"
    next_button = "next2"
    order__button_xpath = "/html/body/div[6]/div/div[2]/button"
    name_box_id = "name"
    country_box_id = "country"
    city_box_id = "city"
    card_box_id = "card"
    month_box_id = "month"
    year_box_id = "year"
    pearchus_button_xpath = "//button[contains(text(),'Purchase')]"
    close_button_xpath = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
    successful_xoath = "/html/body/div[10]/div[7]/div/button"
    title_text = "/html/body/div[10]/h2"
    phone_nokia = "Nokia lumia 15"
    htc_one = "/html/body/div[5]/div/div[2]/div/div[7]/div/a/img"
    title = "/html/head/title"


# ------------------------------------------- Laptope locatore ------------------------------------------------
class Home_page_laotope_locatore:
    link_laptope = "Laptops"
    viao_i5 = "/html/body/div[5]/div/div[2]/div/div[1]/div/a/img"
    vaio_i7 = "/html/body/div[5]/div/div[2]/div/div[2]/div/a/img"
    mack_book_air = "/html/body/div[5]/div/div[2]/div/div[3]/div/a/img"
    Dell_i7 = "/html/body/div[5]/div/div[2]/div/div[4]/div/a/img"
    Dell_2017 = "/html/body/div[5]/div/div[2]/div/div[5]/div/a/img"
    mackBook_pro = "/html/body/div[5]/div/div[2]/div/div[6]/div/a/img"
    title_vaio = "/html/body/div[6]/div/div[1]/div/table/tbody/tr/td[2]"
    title_vaio_i7 = "/html/body/div[6]/div/div[1]/div/table/tbody/tr/td[2]"
    title_macbook = "/html/body/div[6]/div/div[1]/div/table/tbody/tr/td[2]"
    dell = "/html/body/div[6]/div/div[1]/div/table/tbody/tr/td[2]"
    order__button_xpath = "/html/body/div[6]/div/div[2]/button"
    name_box_id = "name"
    country_box_id = "country"
    city_box_id = "city"
    card_box_id = "card"
    month_box_id = "month"
    year_box_id = "year"
    pearchus_button_xpath = "//button[contains(text(),'Purchase')]"
    close_button_xpath = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
    successful_xoath = "/html/body/div[10]/div[7]/div/button"
    title_text = "//h2[contains(text(),'Thank you for your purchase!')]"
    title = "/html/head/title"


# -------------------------------------------------------------- monitore locatore -----------------------------------
class Moniter_device:
    monitore_device_link_texs = "Monitors"
    apple24_xpath = "/html/body/div[5]/div/div[2]/div/div[1]/div/a/img"
    assus_HD_xpath = "/html/body/div[5]/div/div[2]/div/div[2]/div/a/img"
    add_cart = "Add to cart"
    cart_button = "//a[@id='cartur']"
    order__button_xpath = "/html/body/div[6]/div/div[2]/button"
    name_box_id = "name"
    country_box_id = "country"
    city_box_id = "city"
    card_box_id = "card"
    month_box_id = "month"
    year_box_id = "year"
    pearchus_button_xpath = "//button[contains(text(),'Purchase')]"
    close_button_xpath = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
    successful_xoath = "/html/body/div[10]/div[7]/div/button"
    title_text = "//h2[contains(text(),'Thank you for your purchase!')]"
    title = "/html/head/title"
